package com.samplespace.decide;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	private java.lang.Integer claimAmount;
	@org.kie.api.definition.type.Label("Claim Reason")
	private java.lang.String claimReason;
	@org.kie.api.definition.type.Label("Path Value")
	private String pathValue;

	public ClaimObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getClaimAmount() {
		return this.claimAmount;
	}

	public void setClaimAmount(java.lang.Integer claimAmount) {
		this.claimAmount = claimAmount;
	}

	public java.lang.String getClaimReason() {
		return this.claimReason;
	}

	public void setClaimReason(java.lang.String claimReason) {
		this.claimReason = claimReason;
	}

	public java.lang.String getPathValue() {
		return this.pathValue;
	}

	public void setPathValue(java.lang.String pathValue) {
		this.pathValue = pathValue;
	}

	public ClaimObject(java.lang.String name, java.lang.Integer claimAmount,
			java.lang.String claimReason, java.lang.String pathValue) {
		this.name = name;
		this.claimAmount = claimAmount;
		this.claimReason = claimReason;
		this.pathValue = pathValue;
	}

}